# Usa la imagen base de Python 3.11
FROM python:3.11.9

# Establece el directorio de trabajo en el contenedor
WORKDIR /app

# Copia el archivo de requisitos al contenedor
COPY ./dockerfiles/6.App_streamlit/requisitos.txt /app/requisitos.txt

# Instala las dependencias
RUN pip install --no-cache-dir -r requisitos.txt

EXPOSE 8501

HEALTHCHECK CMD curl --fail http://localhost:8501/_stcore/health

# Define el comando por defecto para listar archivos y ejecutar el script de entrada
CMD ["python", "-m", "streamlit", "run", "app/0_Inicio.py", "--server.port=8501", "--server.address=0.0.0.0"]

