# Usa una imagen base con Python
FROM python:3.9-slim

# Establece el directorio de trabajo
WORKDIR /app

# Copia los archivos necesarios (asegúrate de tener tu archivo 'requisitos.txt')
COPY requisitos.txt ./
COPY app/ ./app

# Instala las dependencias
RUN pip install --no-cache-dir -r requisitos.txt

# Instala streamlit si no está en requisitos.txt
RUN pip install --no-cache-dir streamlit

# Exponer el puerto necesario para la app de streamlit
EXPOSE 8501

# Comando para ejecutar streamlit
CMD ["python", "-m", "streamlit.cli", "run", "app/0_Inicio.py", "--server.port=8501", "--server.address=0.0.0.0"]
