---
# Definición del namespace específico para DBGate
apiVersion: v1
kind: Namespace
metadata:
  name: dbgate
  labels:
    parent: apps  # Etiqueta que indica que pertenece al namespace general "apps"
---
# Configuración del Deployment de DBGate
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbgate-deployment
  namespace: dbgate
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dbgate
  template:
    metadata:
      labels:
        app: dbgate
    spec:
      containers:
      - name: dbgate
        image: dbgate/dbgate
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: dbgate-data
          mountPath: /root/.dbgate
      volumes:
      - name: dbgate-data
        hostPath:
          path: /mnt/data/dbgate/data
---
# Configuración del Servicio para DBGate
apiVersion: v1
kind: Service
metadata:
  name: dbgate-service
  namespace: dbgate
spec:
  selector:
    app: dbgate
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30180  # Puerto fijo en el nodo, asegúrate de que esté disponible
  type: NodePort
