# Usa la imagen base de Python 3.11
FROM python:3.11.9

# Establece el directorio de trabajo en el contenedor
WORKDIR /app

# Copia el archivo de requisitos al contenedor
COPY ./dockerfiles/pisos/requisitos.txt /app/requisitos.txt

# Instala las dependencias
RUN pip install --no-cache-dir -r requisitos.txt

# Copia el archivo de Python al contenedor
COPY ./dockerfiles/pisos/main.py /app/main.py

# Copia el script de entrada al contenedor
COPY ./dockerfiles/pisos/entrypoint.sh /app/entrypoint.sh

# Da permisos de ejecución al script de entrada
RUN chmod +x /app/entrypoint.sh

# Define el comando por defecto para listar archivos y ejecutar el script de entrada
CMD ["python", "-u", "/app/main.py"]
