version: '3.8'

services:
  trovitscript:
    image: srolalau/limpieza_datos:latest
    container_name: limpieza_datos
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - /var/log/cron.log:/var/log/cron.log  # Opcional, para ver los logs de cron
