version: '3.8'

services:
  trovitscript:
    image: 
    container_name: preciopiso
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - /var/log/cron.log:/var/log/cron.log  # Opcional, para ver los logs de cron
