version: '3.8'

services:
  trovitscript:
    image: srolalau/trovit:latest
    container_name: trovitscript
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    entrypoint: /bin/bash
    command: -c "chmod +x /app/entrypoint.sh && /app/entrypoint.sh"
