import streamlit as st

def licencias_text():
    st.markdown("""
        ## Licencias y Condiciones de Uso en las Plataformas Inmobiliarias
        El mercado inmobiliario ha experimentado una transformación significativa en la última década gracias al avance de las tecnologías de la información y la proliferación de plataformas digitales que centralizan datos del sector. Idealista y Trovit son dos de las principales plataformas inmobiliarias en España y a nivel internacional, que ofrecen información crucial sobre el estado del mercado, tanto para alquileres como para la compra de viviendas. Sin embargo, el acceso y uso de los datos proporcionados por estas plataformas están sujetos a licencias y condiciones estrictas, que regulan tanto el uso comercial como el personal de la información.
        ### 1. Licencias en Idealista
        Idealista, como uno de los portales líderes en el sector inmobiliario en España, se protege bajo un marco jurídico que resguarda su propiedad intelectual y los datos que ofrece a los usuarios. A pesar de que no se menciona una licencia estándar, como Creative Commons, los Términos y Condiciones de Uso de Idealista establecen restricciones claras sobre la recolección y el uso de los datos disponibles en su plataforma.
        Una de las principales cláusulas prohíbe el uso de cualquier técnica automatizada para recopilar información de sus listados. Esto incluye, pero no se limita a, el uso de scraping, que es la extracción automática de datos. Este tipo de actividades está explícitamente prohibido debido a que Idealista considera que su base de datos es un activo protegido por derechos de propiedad intelectual. Además, el uso comercial de los datos sin la autorización explícita de Idealista también está vetado. Esto significa que cualquier persona o empresa que quiera utilizar los datos de Idealista con fines de investigación, análisis de mercado o cualquier otro uso que implique redistribución o monetización, debe obtener una licencia especial.
        Por lo tanto, aunque Idealista no especifica una "licencia" como tal en sus términos, su protección se basa en un marco legal que se asemeja a una licencia restrictiva de uso, la cual otorga derechos limitados al usuario sobre el contenido disponible, únicamente para usos personales o de consulta.
        ### 2. Licencias en Trovit
        Por otro lado, Trovit, una plataforma que actúa como agregador de anuncios inmobiliarios (y también de otros sectores como automóviles y empleo), tiene un enfoque similar en cuanto a la protección de los datos. Trovit recopila información de diferentes sitios web y la presenta de manera centralizada, facilitando la búsqueda de anuncios para los usuarios. Sin embargo, al igual que Idealista, Trovit también establece límites estrictos sobre el uso de los datos que ofrece.
        Los Términos y Condiciones de Trovit estipulan que el contenido no puede ser utilizado con fines comerciales sin la autorización explícita de la plataforma. En este sentido, cualquier intento de reventa, redistribución o reutilización de los datos, ya sea de manera manual o automatizada, está prohibido sin el acuerdo correspondiente. Trovit también prohíbe el uso de técnicas de scraping para recolectar datos automáticamente de su plataforma, lo que sugiere una política de protección similar a la de Idealista.
        A diferencia de otras plataformas que podrían otorgar licencias más flexibles, Trovit protege su contenido bajo una especie de licencia implícita de uso no comercial, permitiendo a los usuarios consultar la información, pero no reutilizarla para fines lucrativos sin obtener los permisos necesarios. Además, cualquier intento de explotar los datos sin seguir estos lineamientos puede derivar en sanciones legales, dado que Trovit protege fuertemente su propiedad intelectual.
        """)