# Usa una imagen oficial de Python como imagen base
FROM python:3.9-slim

# Establece el directorio de trabajo en el contenedor
WORKDIR /app

# Copia el archivo de script en el contenedor
COPY ./dockerfiles/test/b.py .

# Ejecuta b.py cuando se inicie el contenedor
CMD ["python", "b.py"]
