name: Docker Build and Publish

on:
  push:
    branches: [ Servidor ]  # Ajusta esto si tu rama principal tiene un nombre diferente

env:
  DOCKER_REPOSITORY: srolalau/vcro_test

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./dockerfiles/test/dockerfile_b  # Especifica la ruta al dockerfile
        push: true
        tags: ${{ env.DOCKER_REPOSITORY }}:latest,${{ env.DOCKER_REPOSITORY }}:${{ github.sha }}
