name: Docker Build and Publish

env:
  DOCKER_REPOSITORY: srolalau/vcro_test
  DOCKERFILE_PATH: dockerfiles/test/dockerfile_b
  DOCKERFILE_DIRECTORY: dockerfiles/test

on:
  push:
    branches: [ Servidor ]
    paths:
      - '${{ env.DOCKERFILE_DIRECTORY }}/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ${{ env.DOCKERFILE_PATH }}
        push: true
        tags: ${{ env.DOCKER_REPOSITORY }}:latest,${{ env.DOCKER_REPOSITORY }}:${{ github.sha }}
